services:

  ollama:
    image: ollama/ollama:latest
    container_name: llm-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    gpus: all

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: llm-frontend

    ports:
      - "8501:8501"

    environment:
      OLLAMA_HOST: http://ollama:11434
      MODEL_NAME: llama3.2:1b

    depends_on:
      ollama:
        condition: service_healthy

    restart: unless-stopped


volumes:
  ollama_data: